### PR TITLE
Inline block process

### PR DESCRIPTION
**Pull request by LaurineDargaud**
See new tag `Model - inline` in `GitHubMarkdown` package.
Tests are in `GHMInlineSplitterTest` class (all green!)

**HOW TO :**
Inspect this code:
```smalltalk
GHMInlineSplitter new start: 'Hello world, _this is an italic text_ and here **a bold passage**. You can also identify `some code` or **nested _formats_ if you want** !!!'
```
It will return an array of inline blocks:

<a href="https://zupimages.net/viewer.php?id=20/21/zw7d.png"></a>

**Covered:**
- bold, italic, strike, inline code
- expandable to add or change markups
- nested formats

**TODO:**
- figures and links

### CODE REVIEW

**Comment by Ducasse** [comment]
Super. Laurine can you 
- remove _ in class and instance variable names.
- add some comments to your classes?
- Do you suppport unclosed markup?

**Comment by LaurineDargaud** [comment]
>     * remove _ in class and instance variable names.
>     * add some comments to your classes?
Yup!
>     * Do you suppport unclosed markup?
No, since when I asked on Discord you answered we need to find opener AND closer markups

**Comment by Ducasse** [comment]
but the line after I mentioned that we should do it as with github. But let it like that for now so that we can see. I prefer that we are not too lose. So this should be good.

**Comment by Ducasse** [comment]
Can you check all the _ and after I will integrate it?
Once your code is integrated I will move all the code to microDown project

**Comment by LaurineDargaud** [comment]
Done

**Comment by Ducasse** [comment]
Super 
est ce que tu peux faire
GHMInlineBlock_v2'
GHMInlineEmphasisProcess >> addBasicTextBlocks [
 	| string_array |

linkOrImageProcess [
 	|linkNameCloser_index |
 	"1. search the linkname closer delimiter"
 	linkNameCloser_index

**Pull request merged**
